### ISSUE TITLE
Specify Python 3.8 in installation line or as requirement

### ISSUE THREAD

**Issue by beroe** [plasma-umass/scalene#148]
My installation kept failing because I used generic `python3` when installing. 

I got dozens of `AttributeError: module 'signal' has no attribute 'raise_signal'`

I noticed that `raise_signal` was introduced in python 3.8, so installed while specifying the version:

    python3.8 -m pip install scalene

And now it is working.

**Comment by emeryberger** [comment]
Thanks - we've fixed this issue (in the repo) and removed the dependency. This will be reflected in the next release.

**Comment by yezifeiafei** [comment]
Can I use scalene with python 3.7？
I still got
`Traceback (most recent call last):
  File "./xxx_reader.py", line 17, in <module>
    from scalene import scalene_profiler
  File "/data/software/miniconda3/lib/python3.7/site-packages/scalene/scalene_profiler.py", line 105, in <module>
    class Scalene:
  File "/data/software/miniconda3/lib/python3.7/site-packages/scalene/scalene_profiler.py", line 201, in Scalene
    __orig_raise_signal = signal.raise_signal
AttributeError: module 'signal' has no attribute 'raise_signal'`

**Comment by lacls** [comment]
I still got the same error. Might you check plz, many thanks.
```
Traceback (most recent call last):
  File "./xxx_reader.py", line 17, in <module>
    from scalene import scalene_profiler
  File "/data/software/miniconda3/lib/python3.7/site-packages/scalene/scalene_profiler.py", line 105, in <module>
    class Scalene:
  File "/data/software/miniconda3/lib/python3.7/site-packages/scalene/scalene_profiler.py", line 201, in Scalene
    __orig_raise_signal = signal.raise_signal
AttributeError: module 'signal' has no attribute 'raise_signal'
```

**Comment by emeryberger** [comment]
Did you try to install this with the latest release? Scalene no longer supports 3.7 and this fact is reflected in the `setup.py` file.

**Comment by mwmix** [comment]
> Did you try to install this with the latest release? Scalene no longer supports 3.7 and this fact is reflected in the `setup.py` file.

I wonder if there is an issue with pip3 and python3.7? I was able to reproduce the same problem after running pip3 install -U scalene. It looks like it is installing version 1.5.4 of scalene.

Checking pypi.org looks like that version is still set to support 3.7 (https://pypi.org/project/scalene/1.5.4/). Maybe that is where the issue lies? Just an incorrect setup.py in the 1.5.4 version that is still up there on pypi?

**Comment by emeryberger** [comment]
Sounds like we need to "yank" 1.5.4. Can you verify that 1.5.3 works with 3.7? Thanks!

**Comment by mwmix** [comment]
@emeryberger I just installed 1.5.3 and all I can get is a "Scalene error: received signal SIGSEGV" even with a trivial application.
```bash
[mwmix@localhost ~]$ cat test2.py
#!/usr/bin/python3

print("Hi mom!")
[mwmix@localhost ~]$ scalene ./test2.py
Scalene error: received signal SIGSEGV
[mwmix@localhost ~]$ python3 --version
Python 3.7.15
[mwmix@localhost ~]$ pip3 list installed | grep scalene
scalene                  1.5.3
[mwmix@localhost ~]$ cat /etc/*-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)
```

**Comment by emeryberger** [comment]
Please try previous versions; let's see if there happens to be an OK one for 3.7. Thanks.
